name: Docker Build

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Login to PCR
        uses: docker/login-action@v1
        with:
          registry: pcr.atslega.network
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm install
      - run: npm install -g react-scripts
      - run: npm run build
      - name: Docker Build & Push
        uses: docker/build-push-action@v1
        with:
          registry: pcr.atslega.network
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          repository: pcr.atslega.network/muehle-altrogge
          tags: latest
